http:
  host: '0.0.0.0'
  port: 9800
  jsonLimit: '50mb'
  bodyLimit: '50mb'

ws:
  port: 15675

db:
  sqlite: 'hmikit.db'

auth:
  jwtExpires: '8h'
  jwtKey: 'secretKey'

log:
  file: './log/hmiServer.log'
  interval: '24h'
  fileSize: '1M'
  maxFiles: 5
  compress: true
  level: 'trace'
